# Generated by Django 5.0.9 on 2024-09-29 18:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_hero_cta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='text_4',
            field=wagtail.fields.RichTextField(blank=True, help_text='Line 4'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_5',
            field=wagtail.fields.RichTextField(blank=True, help_text='Line 5'),
        ),
    ]
