# Generated by Django 5.0.9 on 2024-09-30 10:51

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_badge_image'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_5',
        ),
        migrations.CreateModel(
            name='HomePageSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text_1', models.CharField(blank=True, help_text='Line 1', max_length=255)),
                ('text_2', models.CharField(blank=True, help_text='Line 2 & 3', max_length=255)),
                ('text_3', models.CharField(blank=True, help_text='Line 4', max_length=255)),
                ('text_4', wagtail.fields.RichTextField(blank=True, help_text='Line 4')),
                ('text_5', wagtail.fields.RichTextField(blank=True, help_text='Line 5')),
                ('hero_cta', models.CharField(help_text='Text to display on Call to Action', max_length=255, verbose_name='Hero CTA')),
                ('hero_cta_link', models.ForeignKey(help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero CTA link')),
                ('image', models.ForeignKey(help_text='Slide image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
