# Generated by Django 5.0.9 on 2024-09-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_hero_cta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslide',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
