# Generated by Django 5.0.9 on 2024-09-30 17:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homepage_badge_image_remove_homepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('service_group', 6)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the team member', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Job title of the team member', 'max_length': 100, 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image of the team member', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': "Link to team member's profile", 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('job_title', 1), ('image', 2), ('profile_link', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'help_text': 'Maximum 4 members per service group', 'max_num': 4}), 6: ('wagtail.blocks.StructBlock', [[('members', 5)]], {})}, default=[]),
        ),
    ]
