# Generated by Django 5.0.9 on 2024-10-03 11:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('service_group', 5)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the team member', 'max_length': 100, 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image of the team member', 'required': True}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': "Link to team member's profile", 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1), ('profile_link', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'help_text': 'Maximum 3 members per service group', 'max_num': 3}), 5: ('wagtail.blocks.StructBlock', [[('members', 4)]], {})}, default=[], verbose_name='Services'),
        ),
    ]
