# Generated by Django 5.0.9 on 2024-10-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_aboutuspage_contactuspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AboutUsPage',
        ),
        migrations.DeleteModel(
            name='ContactUsPage',
        ),
    ]
