# Generated by Django 5.0.9 on 2024-10-07 09:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('service_group', 5)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Name of the service', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image of the service', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Description of the service', 'max_length': 1000, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'help_text': 'Maximum 3 members per service group', 'max_num': 4}), 5: ('wagtail.blocks.StructBlock', [[('members', 4)]], {})}, default=[], verbose_name='Services'),
        ),
    ]
