# Generated by Django 5.0.9 on 2024-10-12 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_homepage_body'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageslide',
            old_name='image',
            new_name='image_desktop',
        ),
        migrations.AddField(
            model_name='homepageslide',
            name='image_mobile',
            field=models.ForeignKey(help_text='Slide image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
