# Generated by Django 5.0.9 on 2024-10-12 07:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_image_homepageslide_image_desktop_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslide',
            name='text_6',
            field=wagtail.fields.RichTextField(blank=True, help_text='Line 6'),
        ),
        migrations.AlterField(
            model_name='homepageslide',
            name='image_desktop',
            field=models.ForeignKey(help_text='Slide image for desktop (size 1920x914)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepageslide',
            name='image_mobile',
            field=models.ForeignKey(help_text='Slide image for mobile (size 340x800)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
