# Generated by Django 5.0.9 on 2024-10-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_homepageslide_text_6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageslide',
            name='text_6',
        ),
    ]
