# Generated by Django 5.0.9 on 2024-10-12 08:08

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_homepageslide_text_6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageslide',
            old_name='text_1',
            new_name='text_slide_1',
        ),
        migrations.RenameField(
            model_name='homepageslide',
            old_name='text_2',
            new_name='text_slide_2',
        ),
        migrations.RenameField(
            model_name='homepageslide',
            old_name='text_4',
            new_name='text_slide_4',
        ),
        migrations.RenameField(
            model_name='homepageslide',
            old_name='text_5',
            new_name='text_slide_5',
        ),
        migrations.RemoveField(
            model_name='homepageslide',
            name='text_3',
        ),
        migrations.AddField(
            model_name='homepageslide',
            name='text_slide_3',
            field=models.CharField(blank=True, help_text='Line 4', max_length=255),
        ),
        migrations.AddField(
            model_name='homepageslide',
            name='text_why_choose_us',
            field=wagtail.fields.RichTextField(blank=True, help_text='Line 5'),
        ),
    ]
