# Generated by Django 5.0.9 on 2024-10-12 08:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_text_1_homepageslide_text_slide_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslide',
            name='text_why_choose_us',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text for why choose us'),
        ),
    ]
