# Generated by Django 5.0.9 on 2024-10-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_homepageslide_text_why_choose_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageslide',
            name='text_why_choose_us',
        ),
    ]
