# Generated by Django 5.0.9 on 2024-10-12 08:32

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_homepageslide_text_why_choose_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageWhyChoose',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('why_choose_us', wagtail.fields.RichTextField(blank=True, help_text='Line 4')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
