# Generated by Django 5.0.9 on 2024-10-12 08:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_homepagewhychoose'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='why_choose_us',
            field=wagtail.fields.RichTextField(blank=True, help_text='Paragraph for why choose us'),
        ),
        migrations.DeleteModel(
            name='HomePageWhyChoose',
        ),
    ]
