# Generated by Django 5.0.9 on 2024-10-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Company phone number', max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number', max_length=20)),
                ('address', models.TextField(help_text='Company address')),
                ('postal_code', models.CharField(help_text='Postal code', max_length=10)),
                ('email', models.EmailField(help_text='Company email address', max_length=254)),
                ('facebook', models.URLField(blank=True, help_text='Facebook link')),
                ('twitter', models.URLField(blank=True, help_text='Twitter link')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn link')),
                ('instagram', models.URLField(blank=True, help_text='Instagram link')),
                ('telegram', models.URLField(blank=True, help_text='Telegram link')),
            ],
        ),
    ]
