# Generated by Django 5.0.9 on 2024-10-21 13:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_companyinfo_id_alter_contactmessage_id'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('main_title', models.CharField(blank=True, max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('service_group', 5)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Name of the service', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image of the service', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Description of the service', 'max_length': 1000, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'help_text': 'Maximum 4 members per service group', 'max_num': 4}), 5: ('wagtail.blocks.StructBlock', [[('members', 4)]], {})}, default=[], verbose_name='Services'),
        ),
    ]
