# Generated by Django 5.0.9 on 2024-10-22 08:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_contactuspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('service_group', 9)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Name of the service', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image of the service', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Description of the service', 'max_length': 1000, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Item text', 'required': True}), 4: ('wagtail.blocks.ListBlock', (3,), {'help_text': 'First checklist'}), 5: ('wagtail.blocks.ListBlock', (3,), {'help_text': 'Second checklist'}), 6: ('wagtail.blocks.ListBlock', (3,), {'help_text': 'Third checklist'}), 7: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1), ('second_image', 1), ('description', 2), ('second_description', 2), ('checklist_one', 4), ('checklist_two', 5), ('checklist_three', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Maximum 4 members per service group', 'max_num': 4}), 9: ('wagtail.blocks.StructBlock', [[('members', 8)]], {})}, default=[], verbose_name='Services'),
        ),
    ]
