# Generated by Django 5.0.9 on 2024-10-22 08:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('service_group', 8)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Name of the service', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image of the service', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Description of the service', 'max_length': 1000, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'First checkmark item', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Second checkmark item', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Third checkmark item', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1), ('second_image', 1), ('description', 2), ('second_description', 2), ('checkmark_one', 3), ('checkmark_two', 4), ('checkmark_three', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Maximum 4 members per service group', 'max_num': 4}), 8: ('wagtail.blocks.StructBlock', [[('members', 7)]], {})}, default=[], verbose_name='Services'),
        ),
    ]
