# Generated by Django 5.0.9 on 2024-10-24 08:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslide',
            name='text_slide_1',
            field=wagtail.fields.RichTextField(blank=True, help_text='Line 1', max_length=255),
        ),
    ]
