# Generated by Django 5.0.9 on 2024-10-24 08:23

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_homepageslide_text_slide_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslide',
            name='text_slide_1',
            field=models.CharField(blank=True, help_text='Line 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepageslide',
            name='text_slide_2',
            field=wagtail.fields.RichTextField(blank=True, help_text='Line 2 & 3', max_length=255),
        ),
    ]
