# Generated by Django 5.0.9 on 2024-12-24 09:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_contactmessage_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('service_group', 12)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Name of the service', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image of the service', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Description of the service', 'max_length': 1000, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'First checkmark item', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Second checkmark item', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Third checkmark item', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Meta title for the service page', 'required': False}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Meta description for the service page', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Meta H1 for the service page', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Meta keywords for the service page', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1), ('second_image', 1), ('description', 2), ('second_description', 2), ('checkmark_one', 3), ('checkmark_two', 4), ('checkmark_three', 5), ('meta_title', 6), ('meta_description', 7), ('meta_h1', 8), ('meta_keywords', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'help_text': 'Maximum 4 members per service group', 'max_num': 4}), 12: ('wagtail.blocks.StructBlock', [[('members', 11)]], {})}, default=[], verbose_name='Services'),
        ),
    ]
