# Generated by Django 5.0.9 on 2024-12-24 10:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('service_group', 14)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Slug for the service (autogenerated if left blank)', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Name of the service (used to generate the slug for the URL)', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image of the service', 'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Description of the service above the checkmarks', 'max_length': 1000, 'required': True}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Description of the service below the checkmarks', 'max_length': 1000, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'First checkmark item', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Second checkmark item', 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Third checkmark item', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Meta title for the service page', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Meta description for the service page', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Meta H1 for the service page', 'required': False}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'Meta keywords for the service page', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('slug', 0), ('name', 1), ('image', 2), ('second_image', 2), ('description', 3), ('second_description', 4), ('checkmark_one', 5), ('checkmark_two', 6), ('checkmark_three', 7), ('meta_title', 8), ('meta_description', 9), ('meta_h1', 10), ('meta_keywords', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Maximum 4 members per service group', 'max_num': 4}), 14: ('wagtail.blocks.StructBlock', [[('members', 13)]], {})}, default=[], verbose_name='Services'),
        ),
    ]
